### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bkenned** [tangrams/glmPI#1]
It would be nice to reference clearly from where part of this code context creation was taken http://jan.newmarch.name/RPi/EGL/, or at least be more subtile and do not copy paste the comments at the same time https://github.com/tangrams/glmPI/blob/master/src/main.cpp, because copyrights are clearly given to you in the license.

**Comment by patriciogonzalezvivo** [comment]
Hello Bkenned, thanks for observation. I just push a reference to the RaspberryPI example that comes with the Raspbian distribution from where those lines are ( https://github.com/raspberrypi/firmware/blob/master/opt/vc/src/hello_pi/hello_triangle2/triangle2.c#L100 ). I also add a copy of the Broadcom's license that comes with it.

In relation to the link you provide, I don't remember seen it before. Also seams to be using Broadcom's code too without more reference that:

```
/*
 * code stolen from openGL-RPi-tutorial-master/encode_OGL/
 */
```

I track this reference to this repository ( https://github.com/peepo/openGL-RPi-tutorial ) which unfortunately doesn't have any License or CopyRight attach to it. Which make think he is also using the example codes that comes with the Raspbian distribution. What's your opinion?

Thanks again.

**Comment by bkenned** [comment]
Hi patriciogonzalezvivo,
I think that you're right but it seems that you're using this piece of code in several places, so please do the update. I personally know the author of this book and would like him to be at least referenced if this is from where you got inspired. 
Thanks patriciogonzalezvivo!
Best regards

**Comment by patriciogonzalezvivo** [comment]
Will do! As an author of an on-line book, appreciate your concern and time. I will update the reference to Broadcom's original code, which where was extracted form.

Best!

P

**Comment by bkenned** [comment]
FINE, sorry for the delay.
